name: deploy-practice
# only deploy site from master branch
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2

      - run: echo ${{ steps.get_version.outputs.version-without-v }}

      # https://github.com/actions/checkout
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set env
        run: echo "RELEASE_VERSION=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV 

      # you probably would do build and test steps here

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # deploy the current public folder
          # to <base url>/x.y.z version subfolder
          publish_dir: ./docs
          # destination_dir: "1.00"
          destination_dir: ${{ env.RELEASE_VERSION }}
      # https://github.com/marketplace/actions/github-pages-action
      
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     # deploy the current public folder
      #     # to <base url>/x.y.z version subfolder
      #     publish_dir: ./docs
      #     # destination_dir: "1.00"
      #     destination_dir: "latest"
      - name: Redirect stable to new release
        run: |
          echo "Redirecting latest to newly released version" 
          ln -sf ${{ env.RELEASE_VERSION }} latest
          git config user.name actions-user
          git config user.email action@github.com
          git add latest
          git commit -m "redirect latest to new version ${{ env.RELEASE_VERSION }}"

      # - name: Deploy redirect
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./redirect
      #     keep_files: true