name: deploy-practice
# only deploy site from master branch
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # https://github.com/actions/checkout
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: get_version
        run: echo "RELEASE_VERSION=2.00" >> $GITHUB_ENV

      # you probably would do build and test steps here

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # deploy the current public folder
          # to <base url>/x.y.z version subfolder
          publish_dir: ./docs
          # destination_dir: "1.00"
          destination_dir: ${{ env.RELEASE_VERSION }}

      - name: Redirect latest to new release
        run: |
          echo "Redirecting stable to newly released version" 
          ln -sf $RELEASE_VERSION latest
          git config pull.rebase false
          git pull origin gh-pages
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git add latest
          git commit -m "redirect stable to new version $RELEASE_VERSION"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

      - name: Deploy redirect
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./redirect
          keep_files: true

